// flow-typed signature: 5e196e7d79ec3a8f637ad60851fd4996
// flow-typed version: <<STUB>>/encoding-down_v^6.3.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'encoding-down'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'encoding-down' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'encoding-down/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'encoding-down/index' {
  declare module.exports: $Exports<'encoding-down'>;
}
declare module 'encoding-down/index.js' {
  declare module.exports: $Exports<'encoding-down'>;
}
declare module 'encoding-down/test/index' {
  declare module.exports: $Exports<'encoding-down/test'>;
}
declare module 'encoding-down/test/index.js' {
  declare module.exports: $Exports<'encoding-down/test'>;
}
