// flow-typed signature: fd56379db1593931b71a143c74574b91
// flow-typed version: <<STUB>>/lexicographic-integer_v^1.1.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lexicographic-integer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lexicographic-integer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lexicographic-integer/example/numbers' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/example/pack' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/example/unpack' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/test/big' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/test/hex' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/test/precision' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/test/range' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/test/small' {
  declare module.exports: any;
}

declare module 'lexicographic-integer/test/unpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lexicographic-integer/example/numbers.js' {
  declare module.exports: $Exports<'lexicographic-integer/example/numbers'>;
}
declare module 'lexicographic-integer/example/pack.js' {
  declare module.exports: $Exports<'lexicographic-integer/example/pack'>;
}
declare module 'lexicographic-integer/example/unpack.js' {
  declare module.exports: $Exports<'lexicographic-integer/example/unpack'>;
}
declare module 'lexicographic-integer/index' {
  declare module.exports: $Exports<'lexicographic-integer'>;
}
declare module 'lexicographic-integer/index.js' {
  declare module.exports: $Exports<'lexicographic-integer'>;
}
declare module 'lexicographic-integer/test/big.js' {
  declare module.exports: $Exports<'lexicographic-integer/test/big'>;
}
declare module 'lexicographic-integer/test/hex.js' {
  declare module.exports: $Exports<'lexicographic-integer/test/hex'>;
}
declare module 'lexicographic-integer/test/precision.js' {
  declare module.exports: $Exports<'lexicographic-integer/test/precision'>;
}
declare module 'lexicographic-integer/test/range.js' {
  declare module.exports: $Exports<'lexicographic-integer/test/range'>;
}
declare module 'lexicographic-integer/test/small.js' {
  declare module.exports: $Exports<'lexicographic-integer/test/small'>;
}
declare module 'lexicographic-integer/test/unpack.js' {
  declare module.exports: $Exports<'lexicographic-integer/test/unpack'>;
}
