// flow-typed signature: de52f517be085ad7e2f9a69cccdbcbfe
// flow-typed version: <<STUB>>/require-context_v^1.1.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-context/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-context/index' {
  declare module.exports: $Exports<'require-context'>;
}
declare module 'require-context/index.js' {
  declare module.exports: $Exports<'require-context'>;
}
declare module 'require-context/register.js' {
  declare module.exports: $Exports<'require-context/register'>;
}
